
#    creates a small, separate environment just for dbt. It is used by:
#        - The short-lived dbt service, for running dbt commands manually.
#        - The optional dbt_docs service, for generating and serving the dbt documentation website.


#dbt is a python app; we can use a small Python image
FROM python:3.12-slim

#dbt can use git, not needed for our needs, but may come in handy later
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

# install dbt & POSTGRES connector
RUN pip install --no-cache-dir dbt-postgres==1.11.0

#mount ./dbt to this location
# contains dbt models, tests, project settings, connection profile
WORKDIR /usr/app

#treat later container commands as dbt commands
#eg. `docker compose run --rm dbt build` == `dbt build`.
ENTRYPOINT ["dbt"]